services:
  optimum-server:
    build:
      context: .
      dockerfile: ./YahtzeePro.Optimum.Api/Dockerfile
      target: final
    ports:
      - 8091:8080

  play-server:
    build:
      context: .
      dockerfile: ./YahtzeePro.Play.Api/Dockerfile
      target: final
    ports:
      - 8090:8080
